// sync-env.js
// Reads ONLINE_MEMBERS from the root .env and writes it to client/.env
// as VITE_ONLINE_MEMBERS so Vite can access it at build/dev time.
// Run this before starting the dev server (handled automatically by npm scripts).

const fs   = require('fs');
const path = require('path');

const rootEnvPath   = path.join(__dirname, '.env');
const clientEnvPath = path.join(__dirname, 'client', '.env');

function parseEnv(content) {
  const vars = {};
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx === -1) continue;
    vars[trimmed.slice(0, idx).trim()] = trimmed.slice(idx + 1).trim();
  }
  return vars;
}

if (!fs.existsSync(rootEnvPath)) {
  console.log('sync-env: no root .env found, skipping.');
  process.exit(0);
}

const rootVars     = parseEnv(fs.readFileSync(rootEnvPath, 'utf8'));
const onlineMembers = rootVars['ONLINE_MEMBERS'] ?? '';

let clientContent = fs.existsSync(clientEnvPath)
  ? fs.readFileSync(clientEnvPath, 'utf8')
  : '# Auto-generated by sync-env.js — do not edit VITE_ lines manually\n';

const newLine = `VITE_ONLINE_MEMBERS=${onlineMembers}`;
if (/^VITE_ONLINE_MEMBERS=.*/m.test(clientContent)) {
  clientContent = clientContent.replace(/^VITE_ONLINE_MEMBERS=.*/m, newLine);
} else {
  clientContent = clientContent.trimEnd() + '\n' + newLine + '\n';
}

fs.writeFileSync(clientEnvPath, clientContent);
console.log(`sync-env: VITE_ONLINE_MEMBERS=${onlineMembers || '(empty)'}`);
